### ISSUE TITLE
Support VignetteBuilder as dependency

### ISSUE THREAD

**Issue by hadley** [r-lib/desc#86]
For e.g. https://github.com/r-lib/usethis/issues/773

**Comment by gaborcsardi** [comment]
Hmmmm, `VignetteBuilder` is not like the other dependencies, though, because every package in `VignetteBuilder` must appear in `Imports`, `Depends` or `Suggests`.

So I am not entirely sure what "supporting `VignetteBuilder` as a dependency" means. 

Do we rather want to treat this field specially, e.g. have `set_vignette_builder()` etc. methods?

**Comment by hadley** [comment]
Oooh ok, in that case usethis can handle itself, I think. 

Although maybe desc should have general support for a comma separate field?

**Comment by gaborcsardi** [comment]
Yeah, I guess we could have `get_list()` and `set_list()`? 

Btw. another difference is that real dependency fields can have version requirements, `VignetteBuilder` cannot.
